### ISSUE TITLE
Legends export stuck on "start loading world"

### ISSUE THREAD

**Issue by ngc-6853** [Kromtec/LegendsViewer-Next#17]
Hi!
I asked you on Reddit if you would be interested by my legends export that is not loading, it stays on "Start loading world", here it is: https://dffd.bay12games.com/file.php?id=17243
I kept it running a few hours without success and the LegendsViewer process does not seem to do anything - no CPU usage in Windows task manager.
Maybe it's worth saying I used a custom world gen, and took over the destiny of the Tower of Drills which in year 100, had no fortress (dying civ?)
Also I used some DFHack-ery from time to time, to give necromancy powers or have troglo or gorlaks join my civ.
Let me know if you need something else (save, world gen etc.)
And thank again for the tool, it is amazing as I could see on other worlds!

**Comment by vespakoen** [comment]
The XML contains some ampersand signs (&) which should have been escaped (&amp;) this is probably a bug in the exporter, you can find and replace or remove them from the XML file and then things will work again ;)

**Comment by Kromtec** [comment]
@ngc-6853, as @vespakoen pointed out, the issue here stems from unescaped ampersand characters (&), which are invalid in XML text unless properly escaped.

This is something that needs to be addressed within the Dwarf Fortress export itself. Currently, the game allows nicknames without character restrictions, but any text exported to XML should escape special characters like & to comply with XML standards.
```
...
<historical_figure>
		<id>11234</id>
		<name>muthkat `m1a giant slayer & fb' cudgelruled the triangular lizard</name>
		<race>DWARF</race>
		<caste>MALE</caste>
...
```
@claudiusmueller I am still waiting for the download to finish, but I will look into it ;-)

**Comment by Kromtec** [comment]
@claudiusmueller so I just took a look and your export is corrupted. It stops mid an <written_content> XML node at line 13129281
Nothing that I can do on LegendsViewer side, maybe try to export it a second time.

**Comment by ngc-6853** [comment]
@vespakoen @Kromtec Thank you very much! It is indeed loading after the replacement of "&".
I will try to report this to Bay12!

**Comment by claudiusmueller** [comment]
@Kromtec - thank you for checking. I have re-exported and was able to load into Legends Viewer. Just for feedback - would be nice to have user feedback that a file can't be loaded or is corrupt instead of the forever spinning loader.

But then, that is really nitpicking. Your software is a dream come true. I also REALLY appreciate you making this version OS agnostic. Huge fan.
