### ISSUE TITLE
"All" pagination option in large lists doesn't seem to do anything.

### ISSUE THREAD

**Issue by beatsbury** [Kromtec/LegendsViewer-Next#28]
If applying pagination options to a long list (e.g. show 25, 50, 100 or ALL items) the "All" option doesn't do anithing. At least in Edge browser.

https://github.com/user-attachments/assets/365ed53e-0ad0-4803-b440-833047e5933f

**Comment by silverwing235** [comment]
Can confirm on Reddit: https://www.reddit.com/r/dwarffortress/comments/1gl8gkk/comment/lvzuy0x/

**Comment by Kromtec** [comment]
Thanks for the detailed bug report with video of whats happening.
I will look into it, but I may get rid of the 'All' option anyways, because activating it on something like Events or Written Content where you have thousands of entries would leads to big performance issues without going an extra mile to completely virtualize the table in such cases.

**Comment by beatsbury** [comment]
@Kromtec you're an MVP, thanks for quick update!
